insert into anime_type (type_id,type_name) values 
(1, 'Movie'),
(2, 'TV'),
(3, 'OVA'),
(4, 'Special'),
(5, 'Music'),
(6, 'ONA');

insert into genre(genre_id, genre_name) values
(1, 'Drama'),
(2, 'Romance'),
(3, 'School'),
(4, 'Supernatural'),
(5, 'Action'),
(6, 'Adventure'),
(7, 'Fantasy'),
(8, 'Magic'),
(9, 'Military'),
(10, 'Shounen'),
(11, 'Comedy'),
(12, 'Historical'),
(13, 'Parody'),
(14, 'Samurai'),
(15, 'Sci-Fi'),
(16, 'Thriller'),
(17, 'Sports'),
(18, 'Super Power'),
(19, 'Space'),
(20, 'Slice of Life'),
(21, 'Mecha'),
(22, 'Music'),
(23, 'Mystery'),
(24, 'Seinen'),
(25, 'Martial Arts'),
(26, 'Vampire'),
(27, 'Shoujo'),
(28, 'Horror'),
(29, 'Police'),
(30, 'Psychological'),
(31, 'Demons'),
(32, 'Ecchi'),
(33, 'Josei'),
(34, 'Game'),
(35, 'Shounen Ai'),
(36, 'Dementia'),
(37, 'Harem'),
(38, 'Cars'),
(39, 'Kids'),
(40, 'Shoujo Ai'),
(41, 'Hentai'),
(42, 'Yaoi'),
(43, 'Yuri');